server:
  service: 
    type: LoadBalancer

serverFiles:
  alerting_rules.yml:
    groups:
      - name: alertas_disponibilidade
        rules:
        - alert: TaxaDeFalhasMuitoAlta
          expr: sum(rate(http_request_duration_seconds_count{status_code=~"[45].."}[5m])) / sum(rate(http_request_duration_seconds_count[5m])) > 0.10
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Alta taxa de falhas"
            description: "Mais de 10% das requisições estão falhando nos últimos 5 minutos"
        - alert: TaxaDeFalhasAlta
          expr: sum(rate(http_request_duration_seconds_count{status_code=~"[45].."}[5m])) / sum(rate(http_request_duration_seconds_count[5m])) > 0.05
          for: 1m
          labels:
            severity: high
          annotations:
            summary: "Alta taxa de falhas"
            description: "Mais de 5% das requisições estão falhando nos últimos 5 minutos"
      - name: alertas_latencia
        rules:
        - alert: LatenciaAlta
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
          for: 1m
          labels:
            severity: medium
          annotations:
            summary: "Latência alta"
            description: "A latência de 95% das requisições está acima de 500ms nos últimos 5 minutos"

# Configuração do Alertmanager
alertmanager:
  enabled: true
  service:
    type: LoadBalancer
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'webhook-notifications-default'
      routes:
        - match:
            severity: critical
          receiver: 'webhook-notifications-critical'
          repeat_interval: 15m
        - match:
            severity: high
          receiver: 'webhook-notifications-high'
          repeat_interval: 30m
    receivers:
      - name: 'webhook-notifications-critical'
        # webhook_configs:
        # - url: 'URL_DO_SEU_WEBHOOK'
      - name: 'webhook-notifications-high'
        # webhook_configs:
        # - url: 'URL_DO_SEU_WEBHOOK'
      - name: 'webhook-notifications-default'
        # webhook_configs:
        # - url: 'URL_DO_SEU_WEBHOOK'